FORMAT: 1A

# Movies

Movies is a simple API for managing movies, genres, and actors.

# Group Movies

Resources related to movies.

## Movies Collection [/api/movies]

### List All Movies [GET]

+ Response 200 (application/json)

    [
        {
            "id": "1",
            "url": "/api/movies/1",
            "name": "Fight Club",
            "rating": 79,
            "description": "Fight Club is a 1999 American film based on the 1996 novel of the same name by Chuck Palahniuk. The film was directed by David Fincher, and stars Brad Pitt, Edward Norton and Helena Bonham Carter."
        }
    ]
