FORMAT: 1A

# Movies

Movies is a simple API for managing movies, genres, and actors.

# Group Movies

Resources related to movies.

## Movies Collection [/api/movies]

### List All Movies [GET]

+ Response 200 (application/json)

    [
        {
            "id": 1,
            "url": "/api/movies/1",
            "name": "Fight Club",
            "rating": 79,
            "description": "Fight Club is a 1999 American film based on the 1996 novel of the same name by Chuck Palahniuk. The film was directed by David Fincher, and stars Brad Pitt, Edward Norton and Helena Bonham Carter."
        }
    ]

### Create a New Movie [POST]

+ name (string) - The name of the movie
+ rating (integer) - The rating of the movie
+ description (string) - A description of the movie

+ Request (application/json)

    {
        "name": "Lock, Stock and Two Smoking Barrels",
        "rating": 76,
        "description": "Lock, Stock and Two Smoking Barrels is a 1998 British crime comedy film written and directed by Guy Ritchie, produced by Matthew Vaughn and starring an ensemble cast featuring Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham, Steven Mackintosh, Vinnie Jones, and Sting.",
    }

+ Response 201 (application/json)

    {
        "id": 2,
        "url": "/api/movies/2",
        "name": "Lock, Stock and Two Smoking Barrels",
        "rating": 76,
        "description": "Lock, Stock and Two Smoking Barrels is a 1998 British crime comedy film written and directed by Guy Ritchie, produced by Matthew Vaughn and starring an ensemble cast featuring Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham, Steven Mackintosh, Vinnie Jones, and Sting.",
    }

+ Response 422 (application/json)

    {
        "name": [
            "The name field is required"
        ]
    }

## Movie [/api/movies/{movie_id}]

+ Parameters
    + movie_id (number) - ID of the Movie in the form of an integer

### View a Movie [GET]

+ Response 200 (application/json)

    {
        "id": 2,
        "url": "/api/movies/2",
        "name": "Lock, Stock and Two Smoking Barrels",
        "rating": 76,
        "description": "Lock, Stock and Two Smoking Barrels is a 1998 British crime comedy film written and directed by Guy Ritchie, produced by Matthew Vaughn and starring an ensemble cast featuring Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham, Steven Mackintosh, Vinnie Jones, and Sting.",
    }

### Update a Movie [PUT]

+ name (string) - The name of the movie
+ rating (integer) - The rating of the movie
+ description (string) - A description of the movie

+ Request (application/json)

    {
        "rating": 100,
    }

+ Response 200 (application/json)

    {
        "id": 2,
        "url": "/api/movies/2",
        "name": "Lock, Stock and Two Smoking Barrels",
        "rating": 100,
        "description": "Lock, Stock and Two Smoking Barrels is a 1998 British crime comedy film written and directed by Guy Ritchie, produced by Matthew Vaughn and starring an ensemble cast featuring Jason Flemyng, Dexter Fletcher, Nick Moran, Jason Statham, Steven Mackintosh, Vinnie Jones, and Sting.",
    }

+ Response 422 (application/json)

    {
        "name": [
            "The name field is required"
        ]
    }


### Delete a Movie [DELETE]

+ Response 204

# Group Actors

Resources related to actors.

## Actors Collection [/api/actors]

### List All Actors [GET]

+ Response 200 (application/json)

    [
        {
            "id": 1,
            "url": "/api/actors/1",
            "first_name": "Daniel",
            "middle_name": "Wroughton",
            "last_name": "Craig",
            "dob": "1968-03-02",
            "age": 49,
            "biography": "Daniel Wroughton Craig is an English actor. He trained at the National Youth Theatre and graduated from the Guildhall School of Music and Drama in 1991, before beginning his career on stage. His film debut was in the drama The Power of One."
        }
    ]

### Create a New Actor [POST]

+ first_name (string) - The actors first name
+ middle_name (string) - The actors middle name
+ last_name (string) - The actors last name
+ dob (date) - The date of birth of the actor
+ biography (string) - A biography of the actor

+ Request (application/json)

    {
        "first_name": "Mads",
        "middle_name": "Dittmann",
        "last_name": "Mikkelsen",
        "dob": "1965-11-22",
        "biography": "Mads Dittmann Mikkelsen is a Danish actor. Originally a gymnast and dancer, he began his career as an actor in 1996."
    }

+ Response 201 (application/json)

    {
        "id": 2,
        "url": "/api/actors/2",
        "first_name": "Mads",
        "middle_name": "Dittmann",
        "last_name": "Mikkelsen",
        "dob": "1965-11-22",
        "age": 51,
        "biography": "Mads Dittmann Mikkelsen is a Danish actor. Originally a gymnast and dancer, he began his career as an actor in 1996."
    }

+ Response 422 (application/json)

    {
        "first_name": [
            "The first name field is required"
        ]
    }

## Actor [/api/actors/{actor_id}]

+ Parameters
    + actor_id (number) - ID of the Actor in the form of an integer

### View an Actor [GET]

+ Response 200 (application/json)

    {
        "id": 2,
        "url": "/api/actors/2",
        "first_name": "Mads",
        "middle_name": "Dittmann",
        "last_name": "Mikkelsen",
        "dob": "1965-11-22",
        "age": 51,
        "biography": "Mads Dittmann Mikkelsen is a Danish actor. Originally a gymnast and dancer, he began his career as an actor in 1996."
    }

### Update an Actor [PUT]

+ first_name (string) - The actors first name
+ middle_name (string) - The actors middle name
+ last_name (string) - The actors last name
+ dob (date) - The date of birth of the actor
+ biography (string) - A biography of the actor

+ Request (application/json)

    {
        "biography": "Mads was awesome in Hannibal.",
    }

+ Response 200 (application/json)

    {
        "id": 2,
        "url": "/api/actors/2",
        "first_name": "Mads",
        "middle_name": "Dittmann",
        "last_name": "Mikkelsen",
        "dob": "1965-11-22",
        "age": 51,
        "biography": "Mads was awesome in Hannibal."
    }

+ Response 422 (application/json)

    {
        "first_name": [
            "The first_name field is required"
        ]
    }


### Delete an Actor [DELETE]

+ Response 204

# Group Genres

Resources related to genres.

## Genres Collection [/api/genres]

### List All Genres [GET]

+ Response 200 (application/json)

    [
        {
            "id": 1,
            "url": "/api/genre/1",
            "name": "Action",
        }
    ]

### Create a New Genre [POST]

+ name (string) - The name of the genre

+ Request (application/json)

    {
        "name": "Comedy",
    }

+ Response 201 (application/json)

    {
        "id": 2,
        "url": "/api/genres/2",
        "name": "Comedy",
    }

+ Response 422 (application/json)

    {
        "name": [
            "The name field is required"
        ]
    }

## Genre [/api/genre/{genre_id}]

+ Parameters
    + genre_id (number) - ID of the Genre in the form of an integer

### View a Genre [GET]

+ Response 200 (application/json)

    {
        "id": 2,
        "url": "/api/genres/2",
        "name": "Comedy",
    }

### Update a Genre [PUT]

+ name (string) - The name of the genre

+ Request (application/json)

    {
        "name": "Thriller",
    }

+ Response 200 (application/json)

    {
        "id": 2,
        "url": "/api/genre/2",
        "name": "Thriller",
    }

+ Response 422 (application/json)

    {
        "name": [
            "The name field is required"
        ]
    }


### Delete a Genre [DELETE]

+ Response 204
