version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            DB_HOST: db
            DB_USERNAME: movies
            DB_PASSWORD: movies
            DB_DATABASE: movies
        depends_on:
            - db
    db:
        image: postgres:9.6
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: movies
            POSTGRES_PASSWORD: movies
            POSTGRES_DB: movies
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8080:80
        depends_on:
            - app
volumes:
    db-data:
